
drugs_smi: "data/drugs.smi"
drug_targets_csv: "data/drug_targets.csv"
disease_genes: "data/disease_genes.txt"
ppi_sif: "data/ppi.sif"
target_pdb: "data/target_structures/target.pdb"
disease_up: "data/signatures/disease_up.txt"
disease_down: "data/signatures/disease_down.txt"
drug_sigs: "data/signatures/drug_signatures.csv"

seed: 20250830

weights:
  network: 0.30
  signatures: 0.30
  docking: 0.20
  admet: 0.20
